- name: Setup my server
  # apply this play on all host in the inventory
  hosts: all
  vars:
    install_these:
      nginx: present
      zip: present
  tasks:
  - name: Install nginx
    apt:
      update_cache: yes 
      name: "{{ item.key }}"
      state: "{{ item.value }}"
    loop: "{{ install_these | dict2items }}"
  - name: Add HTML content to /var/www/html
    unarchive:
      src: assets.zip
      dest: /var/www/html
  - name: Start nginx 
    systemd_service:
      daemon_reload: true 
      name: nginx
      enabled: true
      state: started